---

name: kibosh

releases:
  - name: kibosh
    version: latest

stemcells:
  - alias: bosh-warden-boshlite-ubuntu-trusty-go_agent
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: kibosh_node
    instances: 1
    azs: [z1]
    jobs:
      - name: kibosh
        release: kibosh
    properties:
      kibosh:
        username: admin
        password: ((kibosh-password))
        service-id: f448fdea-25b8-41aa-aed4-539d8ace5f32
        helm-chart-dir: charts
        ca-data: ((k8s-cluster-ca-cert))
        server: ((k8s-cluster-server))
        token: ((k8s-cluster-token))
    vm_type: minimal
    cloud_properties:
      tags:
        - allow-ssh
    stemcell: bosh-warden-boshlite-ubuntu-trusty-go_agent
    persistent_disk_type: 5GB
    networks:
      - name: default

variables:
- name: kibosh-password
  type: password