---

resources:
- name: source-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cf-platform-eng/kibosh
    username: cf-pe-bot
    password: {{github_token}}

- name: kibosh-linux
  type: s3
  source:
    bucket: kibosh
    region_name: us-west-2
    versioned_file: kibosh.linux
    access_key_id: {{s3_key_id}}
    secret_access_key: {{s3_secret}}

- name: kibosh-darwin
  type: s3
  source:
    bucket: kibosh
    region_name: us-west-2
    versioned_file: kibosh.darwin
    access_key_id: {{s3_key_id}}
    secret_access_key: {{s3_secret}}

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: source-repo
      trigger: true
  - task: run-tests
    config:
      inputs:
      - name: source-repo
      outputs:
      - name: output
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.9"
      run:
        path: bash
        args:
        - -exc
        - |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega

          export SRC=/go/src/github.com/cf-platform-eng/kibosh
          mkdir -p $SRC
          cp -r source-repo/* $SRC
          cd $SRC
          make bootstrap
          make test

          make build
          cp kibosh.* output/
  - put: kibosh-linux
    params:
      file: output/kibosh.linux
  - put: kibosh-darwin
    params:
      file: output/kibosh.darwin
