---

resources:
- name: source-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cf-platform-eng/pks-generic-broker

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: source-repo
      trigger: true
  - task: run-tests
    config:
      inputs:
      - source-repo
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.9"
    run:
      go get github.com/onsi/ginkgo/ginkgo
      go get github.com/onsi/gomega

      pushd source-repo
      make test
