---
resources:
- name: source-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cf-platform-eng/kibosh
    username: cf-pe-bot
    password: {{github_token}}

- name: release-repo
  type: github-release
  source:
    owner: cf-platform-eng
    repository: kibosh
    access_token: {{github_token}}

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:cf-platform-eng/kibosh
    branch: version
    file: version/version
    initial_version: 0.0.1
    private_key: {{github_deploy_key}}

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: source-repo
      trigger: true
    - get: version
      params:
        bump: patch
  - task: run-tests
    config:
      inputs:
      - name: source-repo
      - name: version
      outputs:
      - name: output
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.9"
      run:
        path: bash
        args:
        - -exc
        - |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega

          export SRC=/go/src/github.com/cf-platform-eng/kibosh
          mkdir -p $SRC
          cp -r source-repo/* $SRC

          pushd $SRC
          make bootstrap
          make test
          make build
          popd

          VERSION=`cat version/version`
          cp $SRC/kibosh.darwin output/kibosh-${VERSION}.darwin
          cp $SRC/kibosh.darwin output/kibosh-${VERSION}.linux

  - put: version
    params:
      file: version/version

  - put: release-repo
    params:
      name: version/version
      tag: version/version
      globs:
      - output/kibosh*.*

